namespace DMMDigital.Migrations
{
    using DMMDigital.Models;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<Context>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            AutomaticMigrationDataLossAllowed = true;
        }

        protected override void Seed(Context context)
        {
            if (!context.settings.Any())
            {

                context.Database.ExecuteSqlCommand(@"INSERT INTO SETTINGS (ID,LANGUAGE,SENSOR_PATH,EXAM_PATH,EXPORT_PATH,SENSOR_MODEL,ACQUIRE_MODE,DRAWING_COLOR,DRAWING_SIZE,TEXT_COLOR,TEXT_SIZE,RULER_COLOR,WATERMARK,FILTER_BRIGHTNESS,FILTER_CONTRAST, FILTER_REVEAL,FILTER_SMART_SHARPEN) VALUES (1,'pt-BR', 'C:\IRay\IRayIntraoral_x86\work_dir', 'C:\WimDesktopDB\img', 'C:\','PLUTO0002X',1,'-65536',5,'-65536',26,'-65536', 1, 0, 0, 0, 0);");

                context.Database.ExecuteSqlCommand(@"INSERT INTO SENSOR VALUES (1, 'PLUTO0001X', 'WIM VITOR T1', 20.0, 30.0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO SENSOR VALUES (2, 'PLUTO0002X', 'WIM VITOR T2', 26.0, 36.0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO SENSOR VALUES (3, 'WIM BEBE', 'WIM BEBE', 26.0, 36.0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO SENSOR VALUES (4, 'TWAIN', 'TWAIN', 20.0, 30.0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO SENSOR VALUES (5, 'CDR ELITE', 'CDR', 26.0, 36.0)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(1, 'BITEWINGS')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(2, 'CHECKUP')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(3, 'FULL MOUTH SERIES (18)')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(4, 'FULL MOUTH SERIES (21)')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(5, 'VERTICAL ENDO')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(6, 'HORIZONTAL ENDO')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(7, 'CENTRAL INFERIOR')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(8, 'CENTRAL SUPERIOR')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(9, 'MANDIBULAR DIREITO')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(10, 'MAXILAR DIREITO')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(11, 'MANDIBULAR ESQUERDO')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(12, 'MAXILAR ESQUERDO')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(13, 'MIGRACAO (5)')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(14, 'MIGRACAO (15)')");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE VALUES(15, 'MIGRACAO (25)')");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(1, 1, 185, 180, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(1, 2, 275, 180, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(1, 3, 365, 180, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(1, 4, 455, 180, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(2, 1, 285, 140, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(2, 2, 355, 140, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(2, 3, 325, 230, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(2, 4, 95, 190, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(2, 5, 195, 190, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(2, 6, 425, 190, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(2, 7, 525, 190, 3)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 1, 250, 140, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 2, 330, 140, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 3, 410, 140, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 4, 250, 230, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 5, 330, 230, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 6, 410, 230, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 7, 90, 150, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 8, 90, 240, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 9, 540, 150, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 10, 540, 240, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 11, 430, 50, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 12, 540, 50, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 13, 430, 340, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 14, 540, 340, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 15, 90, 50, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 16, 210, 50, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 17, 90, 340, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(3, 18, 210, 340, 2)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 1, 190, 150, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 2, 260, 150, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 3, 330, 150, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 4, 400, 150, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 5, 470, 150, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 6, 210, 240, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 7, 290, 240, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 8, 370, 240, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 9, 450, 240, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 10, 90, 160, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 11, 90, 250, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 12, 550, 160, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 13, 550, 250, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 14, 460, 70, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 15, 550, 70, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 16, 460, 340, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 17, 550, 340, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 18, 90, 70, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 19, 180, 70, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 20, 90, 340, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(4, 21, 180, 340, 2)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(5, 1, 150, 135, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(5, 2, 220, 135, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(5, 3, 290, 135, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(5, 4, 360, 135, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(5, 5, 430, 135, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(5, 6, 500, 135, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(5, 7, 150, 225, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(5, 8, 220, 225, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(5, 9, 290, 225, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(5, 10, 360, 225, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(5, 11, 430, 225, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(5, 12, 500, 225, 1)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 1, 135, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 2, 225, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 3, 315, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 4, 405, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 5, 495, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 6, 135, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 7, 225, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 8, 315, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 9, 405, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 10, 495, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 11, 135, 275, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 12, 225, 275, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 13, 315, 275, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 14, 405, 275, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(6, 15, 495, 275, 3)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 1, 200, 110, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 2, 260, 110, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 3, 320, 110, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 4, 380, 110, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 5, 440, 110, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 6, 200, 190, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 7, 260, 190, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 8, 320, 190, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 9, 380, 190, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 10, 440, 190, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 11, 200, 270, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 12, 260, 270, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 13, 320, 270, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 14, 380, 270, 1)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(7, 15, 440, 270, 1)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 1, 200, 110, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 2, 260, 110, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 3, 320, 110, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 4, 380, 110, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 5, 440, 110, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 6, 200, 190, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 7, 260, 190, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 8, 320, 190, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 9, 380, 190, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 10, 440, 190, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 11, 200, 270, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 12, 260, 270, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 13, 320, 270, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 14, 380, 270, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(8, 15, 440, 270, 0)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 1, 135, 135, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 2, 225, 135, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 3, 315, 135, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 4, 405, 135, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 5, 495, 135, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 6, 135, 205, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 7, 225, 205, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 8, 315, 205, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 9, 405, 205, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 10, 495, 205, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 11, 135, 275, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 12, 225, 275, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 13, 315, 275, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 14, 405, 275, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(9, 15, 495, 275, 2)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 1, 135, 135, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 2, 225, 135, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 3, 315, 135, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 4, 405, 135, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 5, 495, 135, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 6, 135, 205, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 7, 225, 205, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 8, 315, 205, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 9, 405, 205, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 10, 495, 205, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 11, 135, 275, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 12, 225, 275, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 13, 315, 275, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 14, 405, 275, 2)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(10, 15, 495, 275, 2)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 1, 135, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 2, 225, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 3, 315, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 4, 405, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 5, 495, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 6, 135, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 7, 225, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 8, 315, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 9, 405, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 10, 495, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 11, 135, 275, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 12, 225, 275, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 13, 315, 275, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 14, 405, 275, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(11, 15, 495, 275, 3)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 1, 135, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 2, 225, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 3, 315, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 4, 405, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 5, 495, 135, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 6, 135, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 7, 225, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 8, 315, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 9, 405, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 10, 495, 205, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 11, 135, 275, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 12, 225, 275, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 13, 315, 275, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 14, 405, 275, 3)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(12, 15, 495, 275, 3)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(13, 1, 220, 170, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(13, 2, 280, 170, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(13, 3, 340, 170, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(13, 4, 400, 170, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(13, 5, 460, 170, 0)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 1, 220, 110, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 2, 280, 110, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 3, 340, 110, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 4, 400, 110, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 5, 460, 110, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 6, 220, 190, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 7, 280, 190, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 8, 340, 190, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 9, 400, 190, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 10, 460, 190, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 11, 220, 270, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 12, 280, 270, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 13, 340, 270, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 14, 400, 270, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(14, 15, 460, 270, 0)");

                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 1, 220, 40, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 2, 280, 40, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 3, 340, 40, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 4, 400, 40, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 5, 460, 40, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 6, 220, 120, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 7, 280, 120, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 8, 340, 120, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 9, 400, 120, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 10, 460, 120, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 11, 220, 200, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 12, 280, 200, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 13, 340, 200, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 14, 400, 200, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 15, 460, 200, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 16, 220, 280, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 17, 280, 280, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 18, 340, 280, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 19, 400, 280, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 20, 460, 280, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 21, 220, 360, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 22, 280, 360, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 23, 340, 360, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 24, 400, 360, 0)");
                context.Database.ExecuteSqlCommand(@"INSERT INTO TEMPLATE_FRAME(TEMPLATE_ID, ORDINATION, LOCATION_X, LOCATION_Y, ORIENTATION) VALUES(15, 25, 460, 360, 0)");
            }

        }
    }
}
