//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMMDigital.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMMDigital.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string banner_principal_f3639437 {
            get {
                return ResourceManager.GetString("banner_principal_f3639437", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grid {
            get {
                object obj = ResourceManager.GetObject("grid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_16x16_fit {
            get {
                object obj = ResourceManager.GetObject("icon_16x16_fit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_16x16_folder {
            get {
                object obj = ResourceManager.GetObject("icon_16x16_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_16x16_original_size {
            get {
                object obj = ResourceManager.GetObject("icon_16x16_original_size", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_16x16_trash {
            get {
                object obj = ResourceManager.GetObject("icon_16x16_trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_16x16_zoom_in {
            get {
                object obj = ResourceManager.GetObject("icon_16x16_zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_16x16_zoom_out {
            get {
                object obj = ResourceManager.GetObject("icon_16x16_zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_arrow {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_autotake {
            get {
                object obj = ResourceManager.GetObject("icon-32x32-autotake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_cancel {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_capture {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_capture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_change_sides {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_change_sides", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_circle {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_compare {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_compare", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_compare_overlap {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_compare_overlap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_compare_side_by_side {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_compare_side_by_side", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_cursor {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_cursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_delete {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_export {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_exposure {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_exposure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_green {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_import {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_import", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_left_arrow {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_left_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_move {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_move", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_new_patient {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_new_patient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_open_exam {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_open_exam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_patients {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_patients", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_pencil {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_rectangle {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_rectangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_recyclebin {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_recyclebin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_red {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_redo {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_reset {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_right_arrow {
            get {
                object obj = ResourceManager.GetObject("icon-32x32-right-arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_rotate_left {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_rotate_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_rotate_right {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_rotate_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_ruler {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_ruler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_scanner {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_scanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_search {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_settings {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_template {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_template", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_text {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_undo {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_32x32_xray_new {
            get {
                object obj = ResourceManager.GetObject("icon_32x32_xray_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        /// </summary>
        internal static System.Drawing.Icon icon_96x96_transparent {
            get {
                object obj = ResourceManager.GetObject("icon_96x96_transparent", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imageConfigFilter {
            get {
                object obj = ResourceManager.GetObject("imageConfigFilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMAGEMBG {
            get {
                object obj = ResourceManager.GetObject("IMAGEMBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seta.
        /// </summary>
        internal static string labelArrow {
            get {
                return ResourceManager.GetString("labelArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Círculo.
        /// </summary>
        internal static string labelEllipse {
            get {
                return ResourceManager.GetString("labelEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desenho Livre.
        /// </summary>
        internal static string labelFreeDraw {
            get {
                return ResourceManager.GetString("labelFreeDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Retângulo.
        /// </summary>
        internal static string labelRectangle {
            get {
                return ResourceManager.GetString("labelRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Régua.
        /// </summary>
        internal static string labelRuler {
            get {
                return ResourceManager.GetString("labelRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Texto.
        /// </summary>
        internal static string labelText {
            get {
                return ResourceManager.GetString("labelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A lixeira já está vazia.
        /// </summary>
        internal static string messageBinAlreadyEmpty {
            get {
                return ResourceManager.GetString("messageBinAlreadyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione mais de uma imagem para comparação..
        /// </summary>
        internal static string messageComparisonSelection {
            get {
                return ResourceManager.GetString("messageComparisonSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configuração Salva !.
        /// </summary>
        internal static string messageConfigSucess {
            get {
                return ResourceManager.GetString("messageConfigSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente realizar a exclusão?.
        /// </summary>
        internal static string messageConfirmDelete {
            get {
                return ResourceManager.GetString("messageConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente esvaziar todas as lixeiras?.
        /// </summary>
        internal static string messageConfirmEmptyAllRecycleBin {
            get {
                return ResourceManager.GetString("messageConfirmEmptyAllRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Todas as Lixeiras foram esvaziadas com sucesso !.
        /// </summary>
        internal static string messageEmptyAllRecycleBinSuccess {
            get {
                return ResourceManager.GetString("messageEmptyAllRecycleBinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao se conectar com banco de dados..
        /// </summary>
        internal static string messageErrorConnectingDatabase {
            get {
                return ResourceManager.GetString("messageErrorConnectingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exame possui imagens, não será possível excluí-lo..
        /// </summary>
        internal static string messageExamCannotDelete {
            get {
                return ResourceManager.GetString("messageExamCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exame não possui nenhuma imagem para exportação.
        /// </summary>
        internal static string messageExamCannotExport {
            get {
                return ResourceManager.GetString("messageExamCannotExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exame excluido com sucesso !.
        /// </summary>
        internal static string messageExamDeleted {
            get {
                return ResourceManager.GetString("messageExamDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao carregar exame.
        /// </summary>
        internal static string messageExamErrorOnLoad {
            get {
                return ResourceManager.GetString("messageExamErrorOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione como deseja exportar a imagem!.
        /// </summary>
        internal static string messageExamExportMode {
            get {
                return ResourceManager.GetString("messageExamExportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exportado com sucesso !.
        /// </summary>
        internal static string messageExamExportSucess {
            get {
                return ResourceManager.GetString("messageExamExportSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exame já está aberto.
        /// </summary>
        internal static string messageExamIsOpened {
            get {
                return ResourceManager.GetString("messageExamIsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum Exame foi selecionado!.
        /// </summary>
        internal static string messageExamNotSelected {
            get {
                return ResourceManager.GetString("messageExamNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja sair sem salvar?.
        /// </summary>
        internal static string messageExitWithoutSave {
            get {
                return ResourceManager.GetString("messageExitWithoutSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exportar as imagens selecionadas?.
        /// </summary>
        internal static string messageExportExam {
            get {
                return ResourceManager.GetString("messageExportExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Obtendo dados....
        /// </summary>
        internal static string messageGettingData {
            get {
                return ResourceManager.GetString("messageGettingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente excluir a imagem atual ?.
        /// </summary>
        internal static string messageImageConfirmDelete {
            get {
                return ResourceManager.GetString("messageImageConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente sobrescrever a imagem atual?.
        /// </summary>
        internal static string messageImageConfirmOverwrite {
            get {
                return ResourceManager.GetString("messageImageConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tem certeza que deseja restaurar a imagem original ?.
        /// </summary>
        internal static string messageImageConfirmRestore {
            get {
                return ResourceManager.GetString("messageImageConfirmRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma Imagem foi selecionada..
        /// </summary>
        internal static string messageImageNotSelected {
            get {
                return ResourceManager.GetString("messageImageNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Importando os dados....
        /// </summary>
        internal static string messageImportData {
            get {
                return ResourceManager.GetString("messageImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Migração do banco de dados feita com sucesso!.
        /// </summary>
        internal static string messageMigrationSuccess {
            get {
                return ResourceManager.GetString("messageMigrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Migração feita com sucesso!.
        /// </summary>
        internal static string messageMigrationSucess {
            get {
                return ResourceManager.GetString("messageMigrationSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Paciente possui exames, não será possível excluí-lo..
        /// </summary>
        internal static string messagePatientCannotDelete {
            get {
                return ResourceManager.GetString("messagePatientCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do Paciente deve ser entre 4 e 65 letras..
        /// </summary>
        internal static string messagePatientConditionName {
            get {
                return ResourceManager.GetString("messagePatientConditionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Paciente cadastrado com sucesso !.
        /// </summary>
        internal static string messagePatientCreated {
            get {
                return ResourceManager.GetString("messagePatientCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Paciente deletado com sucesso !.
        /// </summary>
        internal static string messagePatientDeleted {
            get {
                return ResourceManager.GetString("messagePatientDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As informações do paciente foram atualizadas com sucesso !.
        /// </summary>
        internal static string messagePatientEdited {
            get {
                return ResourceManager.GetString("messagePatientEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum Paciente foi selecionado!.
        /// </summary>
        internal static string messagePatientNotSelected {
            get {
                return ResourceManager.GetString("messagePatientNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de Nascimento é obrigatória!.
        /// </summary>
        internal static string messagePatientRequiredBirthDate {
            get {
                return ResourceManager.GetString("messagePatientRequiredBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do Paciente é obrigatório!.
        /// </summary>
        internal static string messagePatientRequiredName {
            get {
                return ResourceManager.GetString("messagePatientRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Digite o valor de {0} pixels em milímetros.
        /// </summary>
        internal static string messageRecalibrateRuler {
            get {
                return ResourceManager.GetString("messageRecalibrateRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirma salvar o template ?.
        /// </summary>
        internal static string messageSaveTemplate {
            get {
                return ResourceManager.GetString("messageSaveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível conectar o sensor, verifique se o apontamento está correto..
        /// </summary>
        internal static string messageSensorCannotConnect {
            get {
                return ResourceManager.GetString("messageSensorCannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Template selecionado é menor que o template atual..
        /// </summary>
        internal static string messageSwitchTemplateNotAvailable {
            get {
                return ResourceManager.GetString("messageSwitchTemplateNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Troca de Template realizada com sucesso!.
        /// </summary>
        internal static string messageSwitchTemplateSuccess {
            get {
                return ResourceManager.GetString("messageSwitchTemplateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Template não pode ser excluido pois existem exames que o utilizam..
        /// </summary>
        internal static string messageTemplateCannotDelete {
            get {
                return ResourceManager.GetString("messageTemplateCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Template Removido com sucesso !.
        /// </summary>
        internal static string messageTemplateDeleteSucess {
            get {
                return ResourceManager.GetString("messageTemplateDeleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Template Cadastrado com sucesso !.
        /// </summary>
        internal static string messageTemplateFrameSucess {
            get {
                return ResourceManager.GetString("messageTemplateFrameSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do Template é obrigatório!.
        /// </summary>
        internal static string messageTemplateRequiredName {
            get {
                return ResourceManager.GetString("messageTemplateRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha Incorreta.
        /// </summary>
        internal static string messageWrongPassword {
            get {
                return ResourceManager.GetString("messageWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nativo.
        /// </summary>
        internal static string nativeAquireMode {
            get {
                return ResourceManager.GetString("nativeAquireMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Padrão do Sensor.
        /// </summary>
        internal static string textButtonResetCalibration {
            get {
                return ResourceManager.GetString("textButtonResetCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recalibrar.
        /// </summary>
        internal static string textButtonSetCalibration {
            get {
                return ResourceManager.GetString("textButtonSetCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Medição Multipla.
        /// </summary>
        internal static string textCheckBoxMultiRuler {
            get {
                return ResourceManager.GetString("textCheckBoxMultiRuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Horizontal Esquerda.
        /// </summary>
        internal static string textHorizontalLeft {
            get {
                return ResourceManager.GetString("textHorizontalLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Horizontal Direita.
        /// </summary>
        internal static string textHorizontalRight {
            get {
                return ResourceManager.GetString("textHorizontalRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cor.
        /// </summary>
        internal static string textLabelColor {
            get {
                return ResourceManager.GetString("textLabelColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho.
        /// </summary>
        internal static string textLabelSize {
            get {
                return ResourceManager.GetString("textLabelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vertical Baixo.
        /// </summary>
        internal static string textVerticalBottom {
            get {
                return ResourceManager.GetString("textVerticalBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vertical Cima.
        /// </summary>
        internal static string textVerticalTop {
            get {
                return ResourceManager.GetString("textVerticalTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comparação de Imagens.
        /// </summary>
        internal static string titleComparison {
            get {
                return ResourceManager.GetString("titleComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        internal static string titleDelete {
            get {
                return ResourceManager.GetString("titleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inserir Texto.
        /// </summary>
        internal static string titleDialogText {
            get {
                return ResourceManager.GetString("titleDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Editar Paciente.
        /// </summary>
        internal static string titleEditPatient {
            get {
                return ResourceManager.GetString("titleEditPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esvaziar Lixeira.
        /// </summary>
        internal static string titleEmptyRecycleBin {
            get {
                return ResourceManager.GetString("titleEmptyRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir Imagem.
        /// </summary>
        internal static string titleImageDelete {
            get {
                return ResourceManager.GetString("titleImageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restaurar Imagem.
        /// </summary>
        internal static string titleImageRestore {
            get {
                return ResourceManager.GetString("titleImageRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sobrescrever Imagem.
        /// </summary>
        internal static string titleOverwriteImage {
            get {
                return ResourceManager.GetString("titleOverwriteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar Template.
        /// </summary>
        internal static string titleSaveTemplate {
            get {
                return ResourceManager.GetString("titleSaveTemplate", resourceCulture);
            }
        }
    }
}
